global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
      - targets: [localhost:9100]

  - job_name: docker_stats
    static_configs:
      - targets: [localhost:9338]
    metric_relabel_configs:
      - source_labels: [compose_workdir]
        regex: '%{SERVICES_ROOT}/.*'
        action: keep
      - source_labels: [compose_oneoff]
        regex: 'True'
        action: drop
      - regex: 'compose_workdir'
        action: labeldrop

  - job_name: caddy
    static_configs:
      - targets: [localhost:2019]
