global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
      - targets: [localhost:9100]

  - job_name: cadvisor
    static_configs:
      - targets: [localhost:8080]
    honor_timestamps: false
    metric_relabel_configs:
      - source_labels: [container_label_com_docker_compose_project_working_dir]
        regex: '%{SERVICES_ROOT}/.*'
        action: keep
      - regex: 'id|image|container_label_.*'
        action: labeldrop
