- name: Bootstrap
  roles: [bootstrap]
  hosts: [all]
  strategy: linear

- name: Gather Facts
  gather_facts: true
  hosts: [all]

- name: Apply common role
  roles: [common]
  hosts: [all]

- name: Apply dotfiles role
  roles: [dotfiles]
  hosts: [all]

- name: Apply zfs role
  roles: [zfs]
  hosts: [home2]

- name: Apply docker role
  roles: [docker]
  hosts: [all]

- name: Apply vector role
  roles: [vector]
  hosts: [all]

- name: Apply tailscale role
  roles: [tailscale]
  hosts: [aux, home]

- name: Apply wireguard role
  roles: [wireguard]
  hosts: [home]

- name: Apply restic role
  roles: [restic]
  hosts: [all]

- name: Apply services role
  roles: [services]
  hosts: [all]

- name: Apply heartbeat role
  roles: [heartbeat]
  hosts: [all]
