- name: Bootstrap
  hosts: all
  strategy: linear
  gather_facts: false
  tasks:
    - name: Install Python
      raw: |
        command -v python3 >/dev/null && exit
        apt-get update
        apt-get install -y python3-minimal
      register: result
      changed_when: result.stdout != ''

- hosts: all
  roles:
    - common
    - dotfiles
    - tailscale
    - wireguard
    - heartbeat
    - docker
    - vector
    - restic
    - services
