zfs_pools:
  tank:
    device: /dev/disk/by-label/tank
    scrub_schedule: Sun 4:00

sanoid_config:
  tank/archive:
    autosnap: true
    autoprune: true
    daily: 99999999
  tank/media:
    autosnap: true
    autoprune: true
    daily: 7
  tank/sync:
    autosnap: true
    autoprune: true
    hourly: 720
