- name: Install dotfiles
  ansible.builtin.script: install-dotfiles.sh {{ dotfiles_repo | quote }}
  register: result
  changed_when: "'already' not in result.stdout"

- name: Install Utilities
  ansible.builtin.apt:
    name:
      - bash-completion
      - file
      - htop
      - jq
      - rsync
      - tmux
      - tree
      - unar
      - vim
      - wget
