- name: Download Repository Signing Key
  ansible.builtin.shell:
    cmd: |
      command mkdir -p /etc/apt/keyrings
      curl https://repositories.timber.io/public/vector/gpg.3543DB2D0A2BC4B8.key |
      gpg --dearmor --output /etc/apt/keyrings/vector.gpg
    creates: /etc/apt/keyrings/vector.gpg

- name: Add Repository
  ansible.builtin.apt_repository:
    repo: >
      deb
      [signed-by=/etc/apt/keyrings/vector.gpg]
      https://repositories.timber.io/public/vector/deb/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }}
      main
    filename: vector

- name: Install Packages
  ansible.builtin.apt:
    name:
      - vector
      - lm-sensors

- name: Create Environment File
  ansible.builtin.template:
    src: env.j2
    dest: /etc/default/vector
    owner: vector
    group: vector
    mode: go-r
  notify: restart_vector

- name: Remove Default Configuration
  ansible.builtin.file:
    path: /etc/vector/vector.toml
    state: absent

- name: Create Configuration
  ansible.builtin.template:
    src: '{{ item }}.yml.j2'
    dest: /etc/vector/{{ item }}.yml
    owner: vector
    group: vector
    mode: go-r
  loop:
    - logs_journald
    - metrics_host
    - metrics_reboot_required
    - metrics_sensors
    - sinks
  notify: restart_vector

- name: Add User to Required Groups
  ansible.builtin.user:
    name: vector
    groups:
      - docker
      - systemd-journal
    append: true
