- name: Restart Docker
  listen: restart_docker
  ansible.builtin.systemd:
    name: docker.service
    state: restarted

- name: Restart containerd
  listen: restart_containerd
  ansible.builtin.systemd:
    name: containerd.service
    state: restarted

- name: Restart Exporter
  listen: restart_exporter
  ansible.builtin.systemd:
    name: docker-stats-exporter.service
    daemon_reload: true
    state: restarted
