rclone_koofr_username: '{{ secret_rclone_koofr_username }}'
rclone_koofr_password: '{{ secret_rclone_koofr_password }}'

restic_repository: rclone::koofr:/backups/{{ inventory_hostname }}
restic_env:
  RCLONE_KOOFR_USER: '{{ rclone_koofr_username }}'
  RCLONE_KOOFR_PASSWORD: '{{ rclone_koofr_password }}'
restic_files:
  - '{{ services_root }}'
restic_backup_options:
  exclude_if_present: .nobackup
  exclude_larger_than: 128M
restic_forget_options:
  prune: true
  group_by: ''
  keep_within: 1y
restic_schedule: 03:00
