rclone_webdav_url: '{{ secret_rclone_webdav_url }}'
rclone_webdav_username: '{{ secret_rclone_webdav_username }}'
rclone_webdav_password: '{{ secret_rclone_webdav_password }}'

restic_repository: rclone::webdav:/Backups/{{ inventory_hostname }}
restic_env:
  RCLONE_CONFIG: /dev/null
  RCLONE_WEBDAV_URL: '{{ rclone_webdav_url }}'
  RCLONE_WEBDAV_USER: '{{ rclone_webdav_username }}'
  RCLONE_WEBDAV_PASS: '{{ rclone_webdav_password }}'
restic_files:
  - '{{ services_root }}'
restic_backup_options:
  exclude_if_present: .nobackup
  exclude_larger_than: 128M
restic_schedule: 03:00
