rclone_ftps_host: '{{ secret_rclone_ftps_host }}'
rclone_ftps_username: '{{ secret_rclone_ftps_username }}'
rclone_ftps_password: '{{ secret_rclone_ftps_password }}'

restic_repository: rclone::ftp:/Backups/{{ inventory_hostname }}
restic_env:
  RCLONE_CONFIG: /dev/null
  RCLONE_FTP_HOST: '{{ rclone_ftps_host }}'
  RCLONE_FTP_PORT: 990
  RCLONE_FTP_TLS: true
  RCLONE_FTP_USER: '{{ rclone_ftps_username }}'
  RCLONE_FTP_PASS: '{{ rclone_ftps_password }}'
restic_files:
  - '{{ services_root }}'
restic_backup_options:
  exclude_if_present: .nobackup
  exclude_larger_than: 128M
restic_schedule: 03:00
