- name: Install Packages
  ansible.builtin.apt:
    name:
      - restic
      - rclone

- name: Create Environment File
  ansible.builtin.template:
    src: env.j2
    dest: /etc/default/restic
    mode: go-r

- name: Initialize Repository
  ansible.builtin.shell: |
    set -ae
    . /etc/default/restic
    restic init --quiet
  register: result
  failed_when:
    - result.rc != 0
    - "'already exists' not in result.stderr"
  changed_when:
    - result.rc == 0

- name: Restore Backup
  ansible.builtin.shell:
    cmd: |
      set -ae
      . /etc/default/restic
      out=$(restic restore latest --target=/ --verify --quiet 2>&1) ||
      printf %s "$out" | grep -q 'no snapshot found'
      mkdir -p /var/lib/restic
      touch /var/lib/restic/restored
    creates: /var/lib/restic/restored

- name: Create systemd Units
  ansible.builtin.template:
    src: restic.{{ item }}.j2
    dest: /etc/systemd/system/restic.{{ item }}
    mode: ''
  notify: restart_restic
  loop:
    - service
    - timer

- name: Enable systemd Timer
  ansible.builtin.systemd:
    name: restic.timer
    enabled: true
    state: started
