- name: Install Packages
  ansible.builtin.apt:
    name:
      - restic
      - rclone

- name: Create Environment File
  ansible.builtin.template:
    src: env.j2
    dest: /etc/default/restic
    mode: go-r

- name: Initialize Repository
  ansible.builtin.script: init-repo.sh
  register: result
  failed_when:
    - result.rc != 0
    - "'already exists' not in result.stdout"
  changed_when:
    - result.rc == 0

- name: Restore Backup
  ansible.builtin.script: restore.sh {{ inventory_hostname | quote }}
  register: result
  changed_when: "'already restored' not in result.stdout"

- name: Create systemd Units
  ansible.builtin.template:
    src: restic.{{ item }}.j2
    dest: /etc/systemd/system/restic.{{ item }}
    mode: ''
  notify: restart_restic
  loop:
    - service
    - timer

- name: Enable systemd Timer
  ansible.builtin.systemd:
    name: restic.timer
    enabled: true
    state: started

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
