- name: Download Repository Signing Key
  ansible.builtin.shell:
    cmd: |
      command mkdir -p /etc/apt/keyrings
      curl https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.gpg |
      gpg --dearmor --output /etc/apt/keyrings/tailscale.gpg
    creates: /etc/apt/keyrings/tailscale.gpg

- name: Add Repository
  ansible.builtin.apt_repository:
    repo: >
      deb
      [signed-by=/etc/apt/keyrings/tailscale.gpg]
      https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }}
      main
    filename: tailscale

- name: Install Package
  ansible.builtin.apt:
    name: tailscale

- name: Create Environment File
  ansible.builtin.template:
    src: env.j2
    dest: /etc/default/tailscale
    mode: go-r
  notify: restart_tailscale

- name: Create systemd Drop-In Directory
  ansible.builtin.file:
    path: /etc/systemd/system/tailscaled.service.d
    state: directory
    mode: ''

- name: Copy systemd Drop-In
  ansible.builtin.copy:
    src: up.conf
    dest: /etc/systemd/system/tailscaled.service.d/up.conf
    mode: ''

- name: Enable IP Forwarding
  ansible.posix.sysctl:
    name: '{{ item }}'
    value: '1'
  loop:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding
