- name: Create Environment File
  ansible.builtin.template:
    src: env.j2
    dest: /etc/default/heartbeat
    mode: go-r

- name: Create systemd Service
  ansible.builtin.template:
    src: heartbeat.service.j2
    dest: /etc/systemd/system/heartbeat.service
    mode: ''
  notify: restart_heartbeat

- name: Enable systemd Service
  ansible.builtin.systemd:
    name: heartbeat.service
    daemon_reload: true
    enabled: true
    state: started
