- name: Create systemd Service
  template:
    src: heartbeat.service.j2
    dest: /etc/systemd/system/heartbeat.service
  notify: restart_heartbeat

- name: Enable systemd Service
  systemd:
    name: heartbeat.service
    daemon_reload: yes
    enabled: yes
    state: started
