- name: Uninstall snap
  ansible.builtin.apt:
    name: snapd
    purge: true
    state: absent

- name: Remove snap Directory
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/snap'
    state: absent
