- name: Restart SSH
  listen: restart_ssh
  ansible.builtin.systemd:
    name: ssh.service
    state: restarted

- name: Restart Automounts
  listen: restart_automounts
  ansible.builtin.systemd:
    name: '{{ item.key }}.automount'
    daemon_reload: true
    state: restarted
  loop: '{{ mounts | dict2items }}'
  loop_control:
    label: '{{ item.key }}'
