- name: Update Hosts File
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '^([^#]+?\s+){{ ansible_hostname | regex_escape }}(\s+.*)?$'
    replace: '\1{{ inventory_hostname }}\2'

- name: Set Hostname
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'
