- name: Import Depedencies Tasks
  ansible.builtin.import_tasks: dependencies.yml

- name: Import System Tasks
  ansible.builtin.import_tasks: system.yml

- name: Import SSH Tasks
  ansible.builtin.import_tasks: ssh.yml

- name: Import Debian Tasks
  ansible.builtin.import_tasks: debian.yml
  when: ansible_lsb.id == 'Debian'
