- name: Hostname
  ansible.builtin.import_tasks: hostname.yml

- name: Mounts
  ansible.builtin.import_tasks: mounts.yml

- name: Packages
  ansible.builtin.import_tasks: packages.yml

- name: SSH
  ansible.builtin.import_tasks: ssh.yml

- name: Timezone
  ansible.builtin.import_tasks: timezone.yml
