- name: Import Depedencies Tasks
  ansible.builtin.import_tasks: dependencies.yml

- name: Import Hostname Tasks
  ansible.builtin.import_tasks: hostname.yml

- name: Import Mounts Tasks
  ansible.builtin.import_tasks: mounts.yml

- name: Import systemd Tasks
  ansible.builtin.import_tasks: systemd.yml

- name: Import SSH Tasks
  ansible.builtin.import_tasks: ssh.yml

- name: Import Timezone Tasks
  ansible.builtin.import_tasks: timezone.yml

- name: Import Ubuntu Tasks
  ansible.builtin.import_tasks: ubuntu.yml
