- name: Create systemd Mount
  template:
    src: item.mount
    dest: /etc/systemd/system/{{ item.key }}.mount
  loop: '{{ mounts | dict2items }}'
  loop_control:
    label: '{{ item.key }}'

- name: Create systemd Automount
  template:
    src: item.automount
    dest: /etc/systemd/system/{{ item.key }}.automount
  loop: '{{ mounts | dict2items }}'
  loop_control:
    label: '{{ item.key }}'
  notify: restart_automounts

- name: Enable systemd Automount
  systemd:
    name: '{{ item.key }}.automount'
    enabled: yes
    state: started
  loop: '{{ mounts | dict2items }}'
  loop_control:
    label: '{{ item.key }}'
