- name: Create systemd Mount
  ansible.builtin.template:
    src: item.mount
    dest: /etc/systemd/system/{{ item.key }}.mount
    mode: ''
  loop: '{{ mounts | dict2items }}'
  loop_control:
    label: '{{ item.key }}'

- name: Create systemd Automount
  ansible.builtin.template:
    src: item.automount
    dest: /etc/systemd/system/{{ item.key }}.automount
    mode: ''
  loop: '{{ mounts | dict2items }}'
  loop_control:
    label: '{{ item.key }}'
  notify: restart_automounts

- name: Enable systemd Automount
  ansible.builtin.systemd:
    name: '{{ item.key }}.automount'
    enabled: true
    state: started
  loop: '{{ mounts | dict2items }}'
  loop_control:
    label: '{{ item.key }}'
