- name: Download Repository Signing Key
  ansible.builtin.shell:
    cmd: |
      command mkdir -p /etc/apt/keyrings
      curl https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg |
      gpg --dearmor --output /etc/apt/keyrings/docker.gpg
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Repository
  ansible.builtin.apt_repository:
    repo: >
      deb
      [signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }}
      stable
    filename: docker

- name: Install Packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-compose-plugin

- name: Configure Docker Daemon
  ansible.builtin.copy:
    content: '{{ docker_config | to_nice_json }}'
    dest: /etc/docker/daemon.json
    mode: ''
  vars:
    docker_config:
      log-driver: journald
      log-opts:
        labels-regex: '.*'
  notify: restart_docker

- name: Configure Plugins Directory
  ansible.builtin.blockinfile:
    path: /etc/containerd/config.toml
    create: true
    mode: ''
    block: |
      [plugins.opt]
        path = "/usr/local/lib/containerd"
  notify: restart_containerd

- name: Remove Default Plugins Directory
  ansible.builtin.file:
    path: /opt/containerd
    state: absent

- name: Install Exporter
  ansible.builtin.get_url:
    url: https://github.com/jan4843/docker_stats_exporter/releases/download/v0.1.0/docker_stats_exporter-v0.1.0-linux-{{ arch[ansible_architecture] }}
    dest: /usr/local/bin/docker-stats-exporter
    mode: +x
    checksum: sha1:{{ checksum[ansible_architecture] }}
  vars:
    arch:
      x86_64: amd64
      aarch64: arm64
      armv7l: arm
    checksum:
      x86_64: 7f653295df334287499a2b392b30b46e169562d5
      aarch64: 23224503c7e4c040555f6f62ba95012210e4619b
      armv7l: 5584488b76fad668c5d6ec46d1be9eb200c1f4c9
  notify: restart_exporter

- name: Create Exporter systemd Service
  ansible.builtin.copy:
    src: docker-stats-exporter.service
    dest: /etc/systemd/system/docker-stats-exporter.service
    mode: ''
  notify: restart_exporter

- name: Enable Exporter systemd Service
  ansible.builtin.systemd:
    name: docker-stats-exporter.service
    daemon_reload: true
    enabled: true
    state: started
