- name: Download Repository Signing Key
  shell:
    cmd: |
      mkdir -p /etc/apt/keyrings
      curl https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg |
      gpg --dearmor --output /etc/apt/keyrings/docker.gpg
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Repository
  apt_repository:
    repo: >
      deb
      [signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }}
      stable
    filename: docker

- name: Install Packages
  apt:
    name:
      - docker-ce
      - docker-compose-plugin

- name: Configure Plugins Directory
  blockinfile:
    path: /etc/containerd/config.toml
    create: yes
    block: |
      [plugins.opt]
        path = "/usr/local/lib/containerd"
  notify: restart_containerd

- name: Remove Default Plugins Directory
  file:
    path: /opt/containerd
    state: absent
