- name: Add Repository Signing Key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

- name: Add Repository
  apt_repository:
    repo: >
      deb
      https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }}
      stable
    filename: docker

- name: Install Packages
  apt:
    name:
      - docker-ce
      - docker-compose-plugin

- name: Configure Plugins Directory
  blockinfile:
    path: /etc/containerd/config.toml
    create: yes
    block: |
      [plugins.opt]
        path = "/usr/local/lib/containerd"
  notify: restart_containerd

- name: Remove Default Plugins Directory
  file:
    path: /opt/containerd
    state: absent
