- name: Download Repository Signing Key
  ansible.builtin.shell:
    cmd: |
      command mkdir -p /etc/apt/keyrings
      curl https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg |
      gpg --dearmor --output /etc/apt/keyrings/docker.gpg
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Repository
  ansible.builtin.apt_repository:
    repo: >
      deb
      [signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }}
      stable
    filename: docker

- name: Install Packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-compose-plugin

- name: Configure Docker Daemon
  ansible.builtin.copy:
    content: '{{ docker_config | to_nice_json }}'
    dest: /etc/docker/daemon.json
    mode: ''
  vars:
    docker_config:
      log-driver: journald
      log-opts:
        labels-regex: '.*'
  notify: restart_docker

- name: Configure Plugins Directory
  ansible.builtin.blockinfile:
    path: /etc/containerd/config.toml
    create: true
    mode: ''
    block: |
      [plugins.opt]
        path = "/usr/local/lib/containerd"
  notify: restart_containerd

- name: Remove Default Plugins Directory
  ansible.builtin.file:
    path: /opt/containerd
    state: absent

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
