- name: Gather Services
  ansible.builtin.script: gather-services.sh {{ services_root | quote }}
  register: services
  changed_when:
    - services.rc == 100
  failed_when:
    - services.rc != 0
    - services.rc != 100

- name: Start Service
  ansible.builtin.script: start-service.sh {{ services_root | quote }}/{{ item | quote }}
  register: result
  changed_when: "'Starting' in result.stdout"
  loop: '{{ services.stdout_lines }}'

- name: Create link-services-crontabs systemd Unit
  ansible.builtin.template:
    src: link-services-crontabs.{{ item }}.j2
    dest: /etc/systemd/system/link-services-crontabs.{{ item }}
    mode: ''
  loop:
    - path
    - service
  notify: link_services_crontabs

- name: Enable link-services-crontabs systemd Path
  ansible.builtin.systemd:
    name: link-services-crontabs.path
    enabled: true
    state: started
