- name: Gather Services
  script: gather-services.sh {{ services_root | quote }}
  register: services
  changed_when:
    - services.rc == 100
  failed_when:
    - services.rc != 0
    - services.rc != 100

- name: Start Service
  script: start-service.sh {{ services_root | quote }}/{{ item | quote }}
  register: result
  changed_when: "'Starting' in result.stdout"
  loop: '{{ services.stdout_lines }}'

- name: Link Services crontab
  file:
    path: /etc/cron.d/services
    src: '{{ services_root }}/crontab'
    state: link
