- name: Gather Services
  ansible.builtin.script: gather-services.sh {{ services_root | quote }}
  register: services
  changed_when:
    - services.rc == 100
  failed_when:
    - services.rc != 0
    - services.rc != 100

- name: Start Service
  ansible.builtin.script: start-service.sh {{ services_root | quote }}/{{ item | quote }}
  register: result
  changed_when: "'Starting' in result.stdout"
  loop: '{{ services.stdout_lines }}'

- name: Create Services crontab
  ansible.builtin.copy:
    dest: '{{ services_root }}/crontab'
    content: ''
    force: false
    mode: ''

- name: Link Services crontab
  ansible.builtin.file:
    path: /etc/cron.d/services
    src: '{{ services_root }}/crontab'
    state: link
