tailscale_options:
  accept_dns: false
  accept_routes: true
  advertise_exit_node: true
  advertise_routes:
    - "{{ (ansible_default_ipv4.address + '/25') | ansible.utils.ipaddr('network') }}/25"
  snat_subnet_routes: true
