zfs_pools:
  tank:
    device: /dev/disk/by-label/tank
    scrub_schedule: Sun 4:00

sanoid_config:
  tank/archive:
    autosnap: true
    autoprune: true
    hourly: 0
    daily: 99999999
    monthly: 0
    yearly: 0
  tank/media:
    autosnap: true
    autoprune: true
    hourly: 0
    daily: 7
    monthly: 0
    yearly: 0
