- name: Install Package
  ansible.builtin.apt:
    name: wireguard

- name: Create Configuration
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: go-r
  notify: restart_wireguard

- name: Enable systemd Service
  ansible.builtin.systemd:
    name: wg-quick@wg0.service
    enabled: true
    state: started

- name: Enable IP Forwarding
  ansible.posix.sysctl:
    name: '{{ item }}'
    value: '1'
  loop:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
